# Generated by Django 2.2 on 2019-04-12 14:48

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190412_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(choices=[('NEW', 'New'), ('XXX', 'Canceled'), ('INP', 'In progress'), ('CMP', 'Completed')], default='NEW', max_length=50),
        ),
    ]
